[package]
name = "eth_address"
version = "0.1.0"
authors = ["yunweb <3358621@qq.com>"]
edition = "2018"

[dependencies]
rand = "0.8.4"
hex = "0.4.3"
async-std = "1.10.0"
num_cpus = "1.13.0"
ethkey = { path = "./ethkey" }
